# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Should I Stay or Should I Go: Anticipatory Intent Prediction for Adaptive Robot-to-Human Handover"
email: f.iori@santannpisa.it
description: >- # this means to ignore newlines until "baseurl:"
    The handover of objects is a fundamental cooperative action in Human-Robot Collaboration (HRC) tasks, requiring the interplay of multiple skills such as perception, coordination, and adaptation. We present a novel method for generating adaptive robot handover trajectories that account for unmodeled perturbations during the handover. The approach draws inspiration from biological anticipatory control to detect human engagement during the handover, dynamically adjusting the trajectory to slow down or stop when perturbations are detected and resuming once the interaction continues. The method requires minimal perception data, making it computationally efficient, practical to deploy, and adaptable for various handover scenarios. Experimental evaluations demonstrate the system's robustness in handling both standard and perturbed handover conditions,  offering a solution for safer and fluent human-robot interaction.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: fraiori0

# Build settings
markdown: kramdown
theme: minima
plugins:
    - jekyll-feed

<link rel="stylesheet" href="{{ '/assets/css/styles.css' | relative_url }}">


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
